version: "3.8"

services:
  localstack:
    image: localstack/localstack:0.12.12
    ports:
      - "4566:4566"
      - "4569:4569"
      - "4571:4571"
      - "4572:4572"
      - "4574:4574"
      - "8080:8080"
    environment:
      - SERVICES=serverless,sqs
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      - "./docker_tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"





